### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by TimB-QNA** [ewandennis/geotiff2stl#1]
I got the following error on running the code:
ValueError: <COMPRESSION.LZW: 5> requires the 'imagecodecs' package

This was fixed by running:
pip install imagecodecs

Please add  imagecodecs to the requirements file.

**Comment by mad-man-moon** [comment]
I have the same issue. Moreover, once imagecodecs is installed, I run into the following error:
`Traceback (most recent call last):
  File "C:\Users\user\Documents\git-misc\geotiff2stl\tiff2stl.py", line 2, in <module>
    import skimage as ski
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\skimage\__init__.py", line 122, in <module>
    from ._shared import geometry
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`
I believe this is with Python 3.11
